# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3.4'

networks:
  reaction:
    external:
      name: reaction.localhost

services:
  mongo:
    image: mongo:4.2.0
    networks:
      default:
      reaction:
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db

